const mongoose=require('mongoose');
const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path'),bcrypt=require('bcrypt'),jwt=require('jsonwebtoken');require('dotenv').config();
const app=express(),port=process.env.PORT||process.env.port||5000,JWT_SECRET=process.env.JWT_SECRET||'change-this-secret-in-production',FRONTEND_URL=process.env.FRONTEND_URL||'',ADMIN_PIN=process.env.ADMIN_SECURITY_PIN||'',ADMIN_ENTRY_CODE=process.env.ADMIN_ENTRY_CODE||'',DATA_FILE=path.join(__dirname,'data.json');
const ENV_ADMIN={username:process.env.ADMIN_USERNAME||'Kaleem Ullah Khan Durrani',email:process.env.ADMIN_EMAIL||'admin@sajidshoes.local',password:process.env.ADMIN_PASSWORD||''};
app.use(cors({origin(o,cb){const a=['http://localhost:5173','http://localhost:5174',FRONTEND_URL].filter(Boolean);if(!o||a.includes(o)||/^https:\/\/[^/]+\.vercel\.app$/.test(o))return cb(null,true);cb(new Error('CORS: frontend origin is not allowed'));},credentials:true}));app.use(express.json({limit:'15mb'}));app.use(express.urlencoded({extended:true,limit:'15mb'}));
const blankState=()=>({products:[],customers:[],bills:[],expenses:[],incomes:[],purchases:[]});
const emptyDB=()=>({state:blankState(),users:[],userStates:{},protectedSnapshots:{},adminRestoreDrafts:{},archives:{},deletedUsers:[],restoreNotices:{},resetRequests:[],settings:{}});
const recordCount=s=>Object.values(s||{}).reduce((n,a)=>n+(Array.isArray(a)?a.length:0),0);
function protectSnapshot(db,id,state,reason){if(!recordCount(state))return;db.protectedSnapshots=db.protectedSnapshots||{};const copy=structuredClone(state);const digest=require("crypto").createHash("sha256").update(JSON.stringify(copy)).digest("hex");if(db.protectedSnapshots[id]?.digest===digest)return;const prior=db.protectedSnapshots[id];db.protectedSnapshots[id]={state:copy,digest,createdAt:new Date().toISOString(),reason};}
function bestProtectedState(db,id){const current=db.userStates[id]||blankState();const protectedState=db.protectedSnapshots?.[id]?.state;/* The live account is authoritative while it has records. A larger historical snapshot must not silently undo intentional edits. */return recordCount(current)?current:(protectedState||current);}
let liveDB=null, mongoWrites=Promise.resolve();
const StoredDB=mongoose.model('AppDatabase',new mongoose.Schema({_id:String,payload:mongoose.Schema.Types.Mixed},{strict:false,versionKey:false}));
function readDB(){if(liveDB)return structuredClone(liveDB);try{return Object.assign(emptyDB(),JSON.parse(fs.readFileSync(DATA_FILE,'utf8')))}catch{return emptyDB()}}
function writeDB(db){liveDB=structuredClone(db);fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2));if(mongoose.connection.readyState===1){const snapshot=structuredClone(db);mongoWrites=mongoWrites.catch(e=>console.error('Previous database save failed:',e)).then(()=>StoredDB.replaceOne({_id:'main'},{_id:'main',payload:snapshot},{upsert:true}));}}
 function tok(p,e='7d'){return jwt.sign(p,JWT_SECRET,{expiresIn:e})} function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer\s+/i,''),JWT_SECRET);next()}catch{return res.status(401).json({message:'Unauthorized'})}} function adminOnly(req,res,next){if(req.user.role!=='admin')return res.status(403).json({message:'Admin only'});next()}
async function adminCreds(db){if(!db.settings.adminPasswordHash)db.settings.adminPasswordHash=await bcrypt.hash(ENV_ADMIN.password,10);return {username:db.settings.adminUsername||ENV_ADMIN.username,email:db.settings.adminEmail||ENV_ADMIN.email,passwordHash:db.settings.adminPasswordHash}}
const publicUser=u=>({id:u.id,username:u.username,email:u.email,approved:u.approved,shopName:u.shopName||'Sajid Shoes',shopLogo:u.shopLogo||'',requestedShopName:u.requestedShopName||'',shopAddress:u.shopAddress||'',shopContact:u.shopContact||'',contactChangePending:u.contactChangePending||null,allowSelfReset:!!u.allowSelfReset,lowStockAlertsEnabled:u.lowStockAlertsEnabled!==false,pages:{...(u.pages||{}),reports:true},createdAt:u.createdAt});
app.get('/health',(_q,r)=>r.json({ok:true,service:'Sajid Shoes API'}));app.get('/api/health',(_q,r)=>r.json({ok:true}));
app.post('/api/auth/register',async(req,res)=>{const username=String(req.body.username||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!username||!email||password.length<6)return res.status(400).json({message:'Email, username and a password of at least 6 characters are required.'});const db=readDB();if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()||u.email===email))return res.status(409).json({message:'Email or username already exists.'});const requestedShopName=String(req.body.requestedShopName||'Sajid Shoes').trim().slice(0,65)||'Sajid Shoes';const id=Date.now().toString();db.users.push({id,username,email,requestedShopName,shopName:'Sajid Shoes',shopLogo:'',shopAddress:'',shopContact:'',contactChangePending:null,passwordHash:await bcrypt.hash(password,10),approved:false,pages:Object.fromEntries(['dashboard','sale','products','stock','purchases','customers','khata','bills','income','reports'].map(x=>[x,true])),createdAt:new Date().toISOString()});db.userStates[id]=blankState();db.archives[id]=[];writeDB(db);res.status(201).json({ok:true,message:'Account created. Waiting for admin approval.'})});
app.post('/api/auth/login',async(req,res)=>{const login=String(req.body.login||req.body.username||'').trim().toLowerCase(),password=String(req.body.password||''),db=readDB(),u=db.users.find(x=>x.username.toLowerCase()===login||x.email===login);if(!u||!await bcrypt.compare(password,u.passwordHash))return res.status(401).json({message:'Invalid email/username or password.'});if(!u.approved)return res.status(403).json({message:'Your account is waiting for admin approval.'});res.json({token:tok({id:u.id,username:u.username,role:'user'}),user:{...publicUser(u),role:'user'}})});
app.post('/api/auth/admin/access-code',(req,res)=>{if(String(req.body.code||'').trim()!==ADMIN_ENTRY_CODE)return res.status(401).json({message:'Incorrect admin verification code.'});res.json({ok:true,gateToken:tok({role:'admin-gate'},'5m')})});
app.post('/api/auth/admin/login',async(req,res)=>{let gate;try{gate=jwt.verify(String(req.body.gateToken||''),JWT_SECRET)}catch{return res.status(401).json({message:'Admin verification is required again.'})}if(gate.role!=='admin-gate')return res.status(401).json({message:'Admin verification is required again.'});const login=String(req.body.login||req.body.username||'').trim().toLowerCase(),password=String(req.body.password||''),db=readDB(),a=await adminCreds(db);writeDB(db);if(![a.username.toLowerCase(),a.email.toLowerCase()].includes(login)||!await bcrypt.compare(password,a.passwordHash))return res.status(401).json({message:'Invalid admin email/username or password.'});res.json({ok:true,tempToken:tok({role:'admin-preverify',username:a.username},'5m')})});
app.post('/api/auth/admin/verify-pin',(req,res)=>{try{const t=jwt.verify(String(req.body.tempToken||''),JWT_SECRET);if(t.role!=='admin-preverify'||String(req.body.pin||'')!==ADMIN_PIN)throw 0;{const db=readDB();adminCreds(db).then(a=>res.json({token:tok({role:'admin',username:a.username}),user:{username:a.username,email:a.email,role:'admin'}}))}}catch{return res.status(401).json({message:'Invalid 6-digit private code.'})}});
app.get('/api/auth/me',auth,(req,res)=>{if(req.user.role==='admin')return res.json({token:tok({role:'admin',username:req.user.username}),user:{username:req.user.username,role:'admin'}});const db=readDB(),u=db.users.find(x=>x.id===req.user.id);if(!u||!u.approved)return res.status(403).json({message:'Account unavailable or not approved.'});res.json({token:tok({id:u.id,username:u.username,role:'user'}),user:{...publicUser(u),role:'user'}})});
app.get('/api/state',auth,(req,res)=>{if(req.user.role!=='user')return res.status(403).json({message:'User account required'});const db=readDB(),stored=db.userStates[req.user.id];res.json({data:stored?JSON.parse(JSON.stringify(stored)):blankState(),restoreNotice:(db.restoreNotices||{})[req.user.id]||null})});
app.post('/api/state',auth,async(req,res)=>{try{if(req.user.role!=='user')return res.status(403).json({message:'User account required'});const db=readDB(),id=req.user.id,old=db.userStates[id]||blankState(),s=req.body||{};const next={products:Array.isArray(s.products)?s.products:[],customers:Array.isArray(s.customers)?s.customers:[],bills:Array.isArray(s.bills)?s.bills:[],expenses:Array.isArray(s.expenses)?s.expenses:[],incomes:Array.isArray(s.incomes)?s.incomes:[],purchases:Array.isArray(s.purchases)?s.purchases:[]};const oldCount=Object.values(old).reduce((n,a)=>n+(Array.isArray(a)?a.length:0),0),newCount=Object.values(next).reduce((n,a)=>n+(Array.isArray(a)?a.length:0),0);if(oldCount>0&&newCount===0)return res.status(409).json({message:'Empty browser state was not allowed to erase saved account data.'});protectSnapshot(db,id,old,"last-synced-before-change");db.archives[id]=db.archives[id]||[];db.archives[id].unshift({id:Date.now().toString(),createdAt:new Date().toISOString(),state:JSON.parse(JSON.stringify(old))});db.archives[id]=db.archives[id].slice(0,50);db.userStates[id]=JSON.parse(JSON.stringify(next));if(!db.adminRestoreDrafts?.[id]){db.adminRestoreDrafts=db.adminRestoreDrafts||{};db.adminRestoreDrafts[id]={state:structuredClone(next),updatedAt:new Date().toISOString(),edited:false}}else if(!db.adminRestoreDrafts[id].edited){db.adminRestoreDrafts[id]={state:structuredClone(next),updatedAt:new Date().toISOString(),edited:false}}protectSnapshot(db,id,next,"latest-nonempty-sync");writeDB(db);await mongoWrites;res.json({ok:true})}catch(e){console.error('Account save failed:',e);res.status(503).json({message:'Server could not confirm the account save. Retry when connected; do not clear your browser data.'})}});
// Explicit user reset: preserve admin recovery and a dated safety archive first.
app.post('/api/state/zero',auth,(req,res)=>res.status(403).json({message:'Only an administrator can reset a shop from Admin Control.'}));
app.post('/api/admin/users/:id/zero',auth,adminOnly,async(req,res)=>{
 try{
  if(req.body?.confirmation!=='ADMIN RESET USER SHOP')return res.status(400).json({message:'Confirmation required.'});
  const db=readDB(),id=req.params.id,u=db.users.find(x=>x.id===id);
  if(!u)return res.status(404).json({message:'User not found.'});
  const previous=structuredClone(db.userStates[id]||blankState());
  if(recordCount(previous)){
   protectSnapshot(db,id,previous,'before-admin-authorized-zero');
   db.archives[id]=db.archives[id]||[];
   db.archives[id].unshift({id:'admin-zero-'+Date.now(),createdAt:new Date().toISOString(),reason:'before-admin-authorized-zero',state:previous});
   db.archives[id]=db.archives[id].slice(0,50);
   db.adminRestoreDrafts=db.adminRestoreDrafts||{};
   db.adminRestoreDrafts[id]={state:structuredClone(previous),updatedAt:new Date().toISOString(),edited:true};
  }
  db.userStates[id]=blankState();db.restoreNotices=db.restoreNotices||{};
  db.restoreNotices[id]={restoredAt:new Date().toISOString(),message:'Admin reset this shop to zero. Please refresh your account.'};
  writeDB(db);await mongoWrites;res.json({ok:true,message:'Selected user shop reset; protected recovery retained.'});
 }catch(e){console.error(e);res.status(503).json({message:'Reset could not be confirmed.'})}
});
// Verified account backup import. Never accept a user id from the uploaded file.
app.post('/api/state/clear-reports',auth,async(req,res)=>{try{if(req.user.role!=='user')return res.status(403).json({message:'User account required'});const db=readDB(),id=req.user.id,u=db.users.find(x=>x.id===id);if(!u||!u.allowSelfReset)return res.status(403).json({message:'Ask Admin Control to authorize this destructive action.'});if(req.body?.confirmation!=='CLEAR REPORT DATA')return res.status(400).json({message:'Confirmation required'});const old=structuredClone(db.userStates[id]||blankState());if(recordCount(old)){protectSnapshot(db,id,old,'before-report-permanent-clear');db.archives[id]=db.archives[id]||[];db.archives[id].unshift({id:'report-clear-'+Date.now(),createdAt:new Date().toISOString(),reason:'before-report-permanent-clear',state:old});db.archives[id]=db.archives[id].slice(0,50);db.adminRestoreDrafts=db.adminRestoreDrafts||{};db.adminRestoreDrafts[id]={state:old,updatedAt:new Date().toISOString(),edited:true};}const next=structuredClone(old);next.bills=[];next.incomes=[];next.expenses=[];next.customers=(next.customers||[]).map(c=>({...c,balance:0}));db.userStates[id]=next;u.allowSelfReset=false;writeDB(db);await mongoWrites;res.json({ok:true,data:next,message:'Report records cleared from user account only; latest pre-clear copy retained in Admin View Data.'})}catch(e){res.status(503).json({message:'Protected clear failed; no success confirmed.'})}});
app.post('/api/state/import',auth,(req,res)=>{
 if(req.user.role!=='user')return res.status(403).json({message:'User account required'});
 const raw=req.body?.backup;
 if(!raw||raw.format!=='sajid-shoes-account-backup-v1'||!raw.state||typeof raw.state!=='object')return res.status(400).json({message:'Unsupported backup. Use a Sajid Shoes account backup exported by the admin.'});
 const keys=['products','customers','bills','expenses','incomes','purchases'];
 if(!keys.every(k=>Array.isArray(raw.state[k])))return res.status(400).json({message:'Backup data is incomplete or invalid. Existing account data is unchanged.'});
 if(!keys.some(k=>raw.state[k].length))return res.status(400).json({message:'This backup contains no records. An empty backup cannot replace an account.'});
 const db=readDB(),id=req.user.id;
 const user=db.users.find(u=>u.id===id);
 if(!user)return res.status(403).json({message:'Account unavailable.'});
 if(String(raw.userId)!==String(id))return res.status(403).json({message:'This backup belongs to another account. Ask admin for the correct backup.'});
 const digest=require('crypto').createHash('sha256').update(JSON.stringify(raw.state)).digest('hex');
 db.importHistory=db.importHistory||{};db.importHistory[id]=db.importHistory[id]||[];
 if(db.importHistory[id].includes(digest))return res.json({ok:true,alreadyImported:true,message:'This backup has already been restored. No duplicate records were added.'});
 const current=db.userStates[id]||blankState();
 const currentCount=keys.reduce((n,k)=>n+(current[k]||[]).length,0);
 if(currentCount&&!req.body.confirmReplace)return res.status(409).json({requiresConfirmation:true,message:'This account already contains saved data. Confirm replacement; the existing data will first be saved in admin backup history.'});
 db.archives[id]=db.archives[id]||[];
 db.archives[id].unshift({id:'before-import-'+Date.now(),createdAt:new Date().toISOString(),reason:'before-user-import',state:structuredClone(current)});
 db.archives[id]=db.archives[id].slice(0,50);
 db.userStates[id]=Object.fromEntries(keys.map(k=>[k,structuredClone(raw.state[k])]));protectSnapshot(db,id,db.userStates[id],"restored-backup");
 db.importHistory[id].push(digest);db.importHistory[id]=db.importHistory[id].slice(-100);
 writeDB(db);
 // A failed database write must never be reported as a confirmed save.
 mongoWrites.then(()=>res.json({ok:true,message:'Backup restored to your account. Your previous data was saved in admin backup history.'})).catch(e=>res.status(503).json({message:'Database confirmation failed. Contact admin before trying again.'}));
});
app.get('/api/admin/users/:id/export-backup',auth,adminOnly,(req,res)=>{
 const db=readDB(),u=db.users.find(x=>x.id===req.params.id);
 if(!u)return res.status(404).json({message:'User not found'});
 res.json({format:'sajid-shoes-account-backup-v1',userId:u.id,username:u.username,createdAt:new Date().toISOString(),source:db.adminRestoreDrafts?.[u.id]?'admin-edited-draft':recordCount(db.userStates[u.id])?'current-account':'protected-admin-snapshot',state:db.adminRestoreDrafts?.[u.id]?.state||bestProtectedState(db,u.id)});
});
// One persistent, editable recovery draft per user. Editing never changes live account records.
app.get('/api/admin/users/:id/recovery-draft',auth,adminOnly,(req,res)=>{
 const db=readDB(),id=req.params.id;if(!db.users.some(u=>u.id===id))return res.status(404).json({message:'User not found'});
 const draft=db.adminRestoreDrafts?.[id];res.json({state:draft?.state||bestProtectedState(db,id),updatedAt:draft?.updatedAt||null,edited:!!draft?.edited});
});
app.put('/api/admin/users/:id/recovery-draft',auth,adminOnly,async(req,res)=>{
 try{const db=readDB(),id=req.params.id,keys=Object.keys(blankState()),state=req.body?.state;
 if(!db.users.some(u=>u.id===id))return res.status(404).json({message:'User not found'});
 if(!state||typeof state!=='object'||Array.isArray(state)||keys.some(k=>!Array.isArray(state[k])))return res.status(400).json({message:'All six account sections must be arrays.'});
 const clean=Object.fromEntries(keys.map(k=>[k,structuredClone(state[k])]));db.adminRestoreDrafts=db.adminRestoreDrafts||{};
 db.adminRestoreDrafts[id]={state:clean,updatedAt:new Date().toISOString(),edited:true};writeDB(db);await mongoWrites;
 res.json({ok:true,message:'Recovery draft updated. Live user records remain unchanged.'});
 }catch(e){res.status(503).json({message:'Recovery draft could not be saved.'})}
});
app.post('/api/admin/users/:id/restore-draft',auth,adminOnly,async(req,res)=>{
 try{const db=readDB(),id=req.params.id,draft=db.adminRestoreDrafts?.[id];if(!db.users.some(u=>u.id===id))return res.status(404).json({message:'User not found'});
 if(!draft)return res.status(400).json({message:'No recovery draft. Open View Data first and save an editable draft.'});
 db.archives[id]=db.archives[id]||[];db.archives[id].unshift({id:'before-draft-'+Date.now(),createdAt:new Date().toISOString(),reason:'before-admin-draft-restore',state:structuredClone(db.userStates[id]||blankState())});db.archives[id]=db.archives[id].slice(0,50);
 db.userStates[id]=structuredClone(draft.state);protectSnapshot(db,id,draft.state,'admin-draft-restore');db.restoreNotices=db.restoreNotices||{};db.restoreNotices[id]={restoredAt:new Date().toISOString(),message:'Admin restored the updated recovery data.'};writeDB(db);await mongoWrites;
 res.json({ok:true,message:'Updated recovery draft restored to the user account.'});
 }catch(e){res.status(503).json({message:'Could not confirm restoration in database.'})}
});
app.post('/api/restore-notice/read',auth,(req,res)=>{if(req.user.role!=='user')return res.status(403).json({message:'User account required'});const db=readDB();db.restoreNotices=db.restoreNotices||{};delete db.restoreNotices[req.user.id];writeDB(db);res.json({ok:true})});
app.post('/api/state/request-shop-reset',auth,(req,res)=>{if(req.user.role!=='user')return res.status(403).json({message:'User only'});const db=readDB(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({message:'Account not found'});db.shopResetRequests=db.shopResetRequests||[];if(db.shopResetRequests.some(r=>r.userId===u.id&&r.status==='pending'))return res.json({ok:true,message:'Your reset request is already waiting for admin approval.'});db.shopResetRequests.push({id:Date.now().toString()+'-'+u.id,userId:u.id,username:u.username,status:'pending',createdAt:new Date().toISOString()});writeDB(db);res.json({ok:true,message:'Request sent. Please ask Admin Control for approval.'})});
app.get('/api/admin/shop-reset-requests',auth,adminOnly,(req,res)=>{const db=readDB();res.json({requests:(db.shopResetRequests||[]).filter(r=>r.status==='pending')})});
app.post('/api/admin/shop-reset-requests/:id/approve',auth,adminOnly,(req,res)=>{const db=readDB(),r=(db.shopResetRequests||[]).find(x=>x.id===req.params.id&&x.status==='pending');if(!r)return res.status(404).json({message:'Pending request not found'});const u=db.users.find(x=>x.id===r.userId);if(!u)return res.status(404).json({message:'User not found'});u.allowSelfReset=true;r.status='approved';r.approvedAt=new Date().toISOString();writeDB(db);res.json({ok:true,message:'Approved. User may now reset once; protected recovery is created before reset.'})});
app.patch('/api/admin/users/:id/lowstock-permission',auth,adminOnly,(req,res)=>{const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'User not found'});u.lowStockAlertsEnabled=req.body.enabled===true;writeDB(db);res.json({ok:true,enabled:u.lowStockAlertsEnabled})});
app.patch('/api/admin/users/:id/reset-permission',auth,adminOnly,(req,res)=>{const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'User not found'});u.allowSelfReset=req.body.enabled===true;writeDB(db);res.json({ok:true,allowSelfReset:u.allowSelfReset})});
app.post('/api/state/authorized-zero',auth,async(req,res)=>{try{if(req.user.role!=='user')return res.status(403).json({message:'User only'});const db=readDB(),id=req.user.id,u=db.users.find(x=>x.id===id);if(!u||!u.allowSelfReset)return res.status(403).json({message:'Admin has not enabled shop reset.'});if(req.body.confirmation!=='RESET MY SHOP')return res.status(400).json({message:'Confirmation required'});const previous=structuredClone(db.userStates[id]||blankState());if(recordCount(previous)){protectSnapshot(db,id,previous,'before-authorized-user-reset');db.archives[id]=db.archives[id]||[];db.archives[id].unshift({id:'user-zero-'+Date.now(),createdAt:new Date().toISOString(),reason:'before-authorized-user-reset',state:previous});db.archives[id]=db.archives[id].slice(0,50);db.adminRestoreDrafts=db.adminRestoreDrafts||{};db.adminRestoreDrafts[id]={state:previous,updatedAt:new Date().toISOString(),edited:true};}db.userStates[id]=blankState();u.allowSelfReset=false;writeDB(db);await mongoWrites;res.json({ok:true,message:'Shop reset completed. Protected admin recovery retained.'})}catch(e){res.status(503).json({message:'Reset failed; please check backup before retrying.'})}});
app.get('/api/admin/users',auth,adminOnly,(req,res)=>res.json({users:readDB().users.map(publicUser)}));
app.patch('/api/admin/users/:id/shop',auth,adminOnly,(req,res)=>{
 const name=String(req.body.shopName||'').trim(),logo=String(req.body.shopLogo||'').trim();
 if(!name||name.length>65)return res.status(400).json({message:'Shop name must be 1–65 characters.'});
 if(logo&&(!/^https:\/\/[^\s]+$/i.test(logo)||logo.length>1000))return res.status(400).json({message:'Logo must be a valid HTTPS image URL.'});
 const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'User not found.'});
 u.shopName=name;u.shopLogo='';writeDB(db);res.json({ok:true,message:'Shop identity approved and saved.',user:publicUser(u)});
});
// Shop contact details are administrator-owned; a user can only request a change.
app.patch('/api/admin/users/:id/contact',auth,adminOnly,(req,res)=>{const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'User not found'});const address=String(req.body.shopAddress??u.shopAddress??'').trim(),contact=String(req.body.shopContact??u.shopContact??'').trim();if(address.length>220||contact.length>40)return res.status(400).json({message:'Address or contact is too long'});u.shopAddress=address;u.shopContact=contact;u.contactChangePending=null;writeDB(db);res.json({ok:true,user:publicUser(u)})});
app.post('/api/user/shop-contact-request',auth,(req,res)=>{if(req.user.role!=='user')return res.status(403).json({message:'User only'});const db=readDB(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({message:'Account not found'});if(u.contactChangePending)return res.status(409).json({message:'Your previous request is waiting for admin review'});const proposedContact=String(req.body.shopContact??u.shopContact??'').trim();const proposedAddress=String(req.body.shopAddress??u.shopAddress??'').trim();if(!proposedContact||proposedContact.length>40||proposedAddress.length>220)return res.status(400).json({message:'Enter a valid address and contact number'});u.contactChangePending={proposedContact,proposedAddress,requestedAt:new Date().toISOString()};writeDB(db);res.json({ok:true,message:'Your request has been sent to Admin Control'})});
app.post('/api/admin/users/:id/contact-request',auth,adminOnly,(req,res)=>{const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u||!u.contactChangePending)return res.status(404).json({message:'No pending contact request'});if(req.body.approve===true){u.shopContact=u.contactChangePending.proposedContact;u.shopAddress=u.contactChangePending.proposedAddress??u.shopAddress;}u.contactChangePending=null;writeDB(db);res.json({ok:true,user:publicUser(u)})});
app.patch('/api/admin/users/:id/approve',auth,adminOnly,(req,res)=>{const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'User not found'});u.shopName=String(u.requestedShopName||u.shopName||'Sajid Shoes').trim().slice(0,65)||'Sajid Shoes';u.shopLogo='';const address=String(req.body.shopAddress??u.shopAddress??'').trim(),contact=String(req.body.shopContact??u.shopContact??'').trim();if(address.length>220||contact.length>40)return res.status(400).json({message:'Invalid shop address or contact length'});u.shopAddress=address;u.shopContact=contact;u.approved=true;writeDB(db);res.json({ok:true,shopName:u.shopName})});
app.delete('/api/admin/users/:id',auth,adminOnly,(req,res)=>{const db=readDB(),id=req.params.id,i=db.users.findIndex(x=>x.id===id);if(i<0)return res.status(404).json({message:'User not found'});const [u]=db.users.splice(i,1);db.deletedUsers=db.deletedUsers||[];protectSnapshot(db,id,db.userStates[id],"before-admin-user-delete");db.deletedUsers.unshift({id:'deleted-'+Date.now(),originalUserId:id,username:u.username,email:u.email,shopName:u.shopName,deletedAt:new Date().toISOString(),state:structuredClone(bestProtectedState(db,id)),archives:JSON.parse(JSON.stringify(db.archives[id]||[]))});delete db.userStates[id];delete db.archives[id];db.resetRequests=(db.resetRequests||[]).filter(r=>r.userId!==id);writeDB(db);res.json({ok:true,message:'User deleted. A protected copy of the saved data was kept by Admin.'})});
app.get('/api/admin/deleted-users',auth,adminOnly,(req,res)=>{const db=readDB();res.json({users:(db.deletedUsers||[]).map(u=>({id:u.id,originalUserId:u.originalUserId,username:u.username,email:u.email,shopName:u.shopName,deletedAt:u.deletedAt,records:recordCount(u.state)}))})});
app.get('/api/admin/deleted-users/:id/data',auth,adminOnly,(req,res)=>{const db=readDB(),u=(db.deletedUsers||[]).find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'Protected deleted-account backup not found'});res.json({state:u.state,archives:u.archives||[],username:u.username,deletedAt:u.deletedAt})});
app.patch('/api/admin/users/:id/pages',auth,adminOnly,(req,res)=>{const page=String(req.body.page||''),allowed=['dashboard','sale','products','stock','purchases','customers','khata','bills','income','reports'];if(page==='reports'&&req.body.enabled===false)return res.status(400).json({message:'Reports must remain available to users.'});if(!allowed.includes(page))return res.status(400).json({message:'Invalid page'});const db=readDB(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({message:'User not found'});u.pages={...(u.pages||{}),[page]:!!req.body.enabled};writeDB(db);res.json({ok:true,pages:u.pages})});
app.get('/api/admin/users/:id/data',auth,adminOnly,(req,res)=>{const db=readDB(),id=req.params.id;if(!db.users.some(u=>u.id===id))return res.status(404).json({message:'User not found'});res.json({state:bestProtectedState(db,id),protectedSnapshot:db.protectedSnapshots?.[id]||null,archives:(db.archives[id]||[]).slice(0,15)})});
app.post('/api/admin/users/:id/backup',auth,adminOnly,(req,res)=>{const db=readDB(),id=req.params.id,u=db.users.find(x=>x.id===id);if(!u)return res.status(404).json({message:'User not found'});db.archives[id]=db.archives[id]||[];db.archives[id].unshift({id:Date.now().toString(),createdAt:new Date().toISOString(),state:JSON.parse(JSON.stringify(db.userStates[id]||blankState()))});db.archives[id]=db.archives[id].slice(0,50);writeDB(db);res.json({ok:true,message:'Protected backup saved successfully.'})});
app.post('/api/admin/users/:id/restore/:archiveId',auth,adminOnly,(req,res)=>{const db=readDB(),id=req.params.id,a=(db.archives[id]||[]).find(x=>String(x.id)===String(req.params.archiveId));if(!a)return res.status(404).json({message:'Backup not found'});db.archives[id]=db.archives[id]||[];db.archives[id].unshift({id:'safety-'+Date.now(),createdAt:new Date().toISOString(),reason:'before-admin-restore',state:JSON.parse(JSON.stringify(db.userStates[id]||blankState()))});db.archives[id]=db.archives[id].slice(0,50);db.userStates[id]=JSON.parse(JSON.stringify(a.state||blankState()));protectSnapshot(db,id,db.userStates[id],"admin-restored");db.restoreNotices=db.restoreNotices||{};db.restoreNotices[id]={backupDate:a.createdAt,restoredAt:new Date().toISOString()};writeDB(db);res.json({ok:true,message:'Saved data restored successfully. User will receive it on login.'})});
app.post('/api/auth/password-reset/request',(req,res)=>{const login=String(req.body.login||'').trim().toLowerCase(),db=readDB(),u=db.users.find(x=>x.username.toLowerCase()===login||x.email===login);if(!u)return res.status(404).json({message:'No account found.'});db.resetRequests=db.resetRequests.filter(x=>!(x.userId===u.id&&!x.used));const r={id:Date.now().toString(),userId:u.id,username:u.username,email:u.email,status:'pending',createdAt:new Date().toISOString(),used:false};db.resetRequests.push(r);writeDB(db);res.json({ok:true,requestId:r.id,message:'Reset request sent to admin.'})});
app.get('/api/auth/password-reset/status/:id',(req,res)=>{const db=readDB(),r=db.resetRequests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({message:'Request not found'});res.json({status:r.status,expiresAt:r.expiresAt||null})});
app.get('/api/admin/reset-requests',auth,adminOnly,(req,res)=>res.json({requests:readDB().resetRequests.filter(x=>!x.used).slice(-30).reverse()}));
app.post('/api/admin/reset-requests/:id/approve',auth,adminOnly,(req,res)=>{const db=readDB(),r=db.resetRequests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({message:'Request not found'});r.status='approved';r.expiresAt=Date.now()+120000;writeDB(db);res.json({ok:true,expiresAt:r.expiresAt})});
app.post('/api/auth/password-reset/complete',async(req,res)=>{const db=readDB(),r=db.resetRequests.find(x=>x.id===String(req.body.requestId||'')),password=String(req.body.password||'');if(!r||r.status!=='approved'||r.used||Date.now()>Number(r.expiresAt||0))return res.status(400).json({message:'Approval is missing or the 2-minute reset window expired.'});if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters.'});const u=db.users.find(x=>x.id===r.userId);u.passwordHash=await bcrypt.hash(password,10);r.used=true;r.status='completed';writeDB(db);res.json({ok:true,message:'Password changed successfully.'})});
app.post('/api/auth/admin/reset/verify-pin',(req,res)=>{if(String(req.body.pin||'')!==ADMIN_PIN)return res.status(401).json({message:'Invalid private 6-digit code.'});res.json({resetToken:tok({role:'admin-reset'},'2m')})});
app.post('/api/auth/admin/reset/complete',async(req,res)=>{try{const t=jwt.verify(String(req.body.resetToken||''),JWT_SECRET);if(t.role!=='admin-reset')throw 0;const password=String(req.body.password||'');if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters.'});const db=readDB();db.settings.adminPasswordHash=await bcrypt.hash(password,10);writeDB(db);res.json({ok:true,message:'Admin password changed.'})}catch{return res.status(400).json({message:'Verification expired. Verify the private code again.'})}});
app.use(express.static(path.join(__dirname,'public')));app.get(/.*/,(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.use((e,_q,r,_n)=>{console.error(e);r.status(500).json({message:e.message||'Server error'})});async function start(){
 if(process.env.MONGODB_URI){
   await mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:15000});
   const saved=await StoredDB.findById('main').lean();
   if(saved?.payload){liveDB=Object.assign(emptyDB(),saved.payload);fs.writeFileSync(DATA_FILE,JSON.stringify(liveDB,null,2));}
   else {liveDB=readDB();await StoredDB.replaceOne({_id:'main'},{_id:'main',payload:liveDB},{upsert:true});}
   console.log('MongoDB connected: account data is database-backed');
 }else if(process.env.NODE_ENV==='production')throw Error('MONGODB_URI is required in production to protect account data across redeploys.');
 else console.warn('Local JSON mode: set MONGODB_URI before deploying for permanent storage.');
 app.listen(port,()=>console.log(`server is running on port ${port}`));
}
start().catch(e=>{console.error('Startup failed:',e.message);process.exit(1)});
